-- CREATE TABLE statement for the 'users' table

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    auth_provider VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    is_email_verified BOOLEAN NOT NULL,
    password VARCHAR(255),
    reset_token VARCHAR(255),
    reset_token_expiry_date TIMESTAMP(6) WITHOUT TIME ZONE,
    username VARCHAR(255) NOT NULL,

    -- Constraints
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT uk_user_reset_token UNIQUE (reset_token),
    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT users_auth_provider_check CHECK (auth_provider IN ('local', 'github', 'google'))
    );


-- CREATE TABLE statement for the 'user_profiles' table

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id BIGINT NOT NULL,
    g_analytics VARCHAR(255),
    github VARCHAR(255) NOT NULL,
    linkedin VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    profile_photo VARCHAR(255) NOT NULL,
    resume_url VARCHAR(255) NOT NULL,
    seo VARCHAR(255),
    title VARCHAR(255) NOT NULL,

    -- Constraints
    CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
    CONSTRAINT fk_user_profiles_users FOREIGN KEY (user_id) REFERENCES users(id)
    );


-- CREATE TABLE statement for the 'skills_category' table

CREATE TABLE IF NOT EXISTS skills_category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(255) NOT NULL,

    -- Constraints
    CONSTRAINT skills_category_pkey PRIMARY KEY (id),
    CONSTRAINT uk_skills_category_category UNIQUE (category)
    );


-- CREATE TABLE statement for the 'skill' table

CREATE TABLE IF NOT EXISTS skill (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    icon VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    skills_category_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT skill_pkey PRIMARY KEY (id),
    CONSTRAINT fk_skill_skills_category FOREIGN KEY (skills_category_id) REFERENCES skills_category(id)
    );


-- CREATE TABLE statement for the 'user_skills' table

CREATE TABLE IF NOT EXISTS user_skills (
    user_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT user_skills_pkey PRIMARY KEY (user_id, skill_id),
    CONSTRAINT fk_user_skills_users FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_skills_skill FOREIGN KEY (skill_id) REFERENCES skill(id)
    );


-- CREATE TABLE statement for the 'project' table

CREATE TABLE IF NOT EXISTS project (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description TEXT NOT NULL,
    github_url VARCHAR(255),
    icon VARCHAR(255),
    live_url VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    video_url VARCHAR(255),
    user_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT project_pkey PRIMARY KEY (id),
    CONSTRAINT fk_project_users FOREIGN KEY (user_id) REFERENCES users(id)
    );


-- CREATE TABLE statement for the 'project_skills' table

CREATE TABLE IF NOT EXISTS project_skills (
    project_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT project_skills_pkey PRIMARY KEY (project_id, skill_id),
    CONSTRAINT fk_project_skills_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_project_skills_skill FOREIGN KEY (skill_id) REFERENCES skill(id)
    );


-- CREATE TABLE statement for the 'project_images' table

CREATE TABLE IF NOT EXISTS project_images (
    project_id BIGINT NOT NULL,
    image_url VARCHAR(255),

    -- Constraints
    CONSTRAINT fk_project_images_project FOREIGN KEY (project_id) REFERENCES project(id)
    );


-- CREATE TABLE statement for the 'publication' table

CREATE TABLE IF NOT EXISTS publication (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    title VARCHAR(255) NOT NULL,
    url VARCHAR(255),
    user_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT publication_pkey PRIMARY KEY (id),
    CONSTRAINT fk_publication_users FOREIGN KEY (user_id) REFERENCES users(id)
    );


-- CREATE TABLE statement for the 'work_experience' table

CREATE TABLE IF NOT EXISTS work_experience (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    company_logo_url VARCHAR(255),
    company_name VARCHAR(255) NOT NULL,
    description TEXT,
    end_date DATE,
    job_title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    start_date DATE NOT NULL,
    user_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT work_experience_pkey PRIMARY KEY (id),
    CONSTRAINT fk_work_experience_users FOREIGN KEY (user_id) REFERENCES users(id)
    );


-- CREATE TABLE statement for the 'experience_skills' table

CREATE TABLE IF NOT EXISTS experience_skills (
    experience_id BIGINT NOT NULL,
    skill_id BIGINT NOT NULL,

    -- Constraints
    CONSTRAINT experience_skills_pkey PRIMARY KEY (experience_id, skill_id),
    CONSTRAINT fk_experience_skills_work_experience FOREIGN KEY (experience_id) REFERENCES work_experience(id),
    CONSTRAINT fk_experience_skills_skill FOREIGN KEY (skill_id) REFERENCES skill(id)
    );